# -*- coding: utf-8 -*-
""" Test pressgloss library. """

# Standard library imports
import unittest

# pressgloss imports
import pressgloss.core as PRESSGLOSS
import pressgloss.helpers as helpers

parsetests = ['FRM (ENG) (FRA  ITA) (PRP (PCE (FRA ITA) ))',
              'FRM (ENG) (FRA ITA) (PRP (PCE (FRA ITA) ))',
              'FRM (ENG) (FRA  ITA) (PRP (PCE (FRA ITA)))',
              'FRM ( ENG) (FRA  ITA) (PRP (PCE (FRA ITA) ))',
              'FRM (ENG) (FRA ITA) (PRP (PCE (ENG FRA ITA)))',
              'FRM (ENG) (FRA ITA) (PRP (ALY (ENG FRA ITA) VSS (RUS TUR)))',
              'FRM (ENG) (FRA ITA) (PRP (ALY (ENG FRA ITA)VSS (RUS TUR)))',
              'FRM (ENG) (FRA ITA) (PRP (ALY (ENG FRA ITA) VSS(RUS TUR)))']

daide20tests = [
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) HLD)))', 'I propose the following move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) MTO YOR)))', 'I propose the following move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (DMZ (FRA ENG) (LVP YOR)))', 'I propose a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (PRP (DMZ (FRA ENG ITA) (LVP YOR)))', 'I propose a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))', 'I propose the following move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))', 'I propose the following move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))', 'I propose the following move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))', 'I propose the following move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) RTO YOR)))', 'I propose the following move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) DSB)))', 'I propose the following move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) BLD)))', 'I propose the following move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG FLT LVP) BLD)))', 'I propose the following move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) REM)))', 'I propose the following move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (XDO (ENG WVE)))', 'I propose the following move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) HLD))))', 'I do not support the following move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR))))', 'I do not support the following move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NOT (DMZ (FRA ENG) (LVP YOR))))', 'I propose that there not be a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR))))', 'I propose that there not be a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I do not support the following move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I do not support the following move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I do not support the following move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I do not support the following move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR))))', 'I do not support the following move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) DSB))))', 'I do not support the following move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) BLD))))', 'I do not support the following move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG FLT LVP) BLD))))', 'I do not support the following move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) REM))))', 'I do not support the following move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO (ENG WVE))))', 'I do not support the following move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) HLD))))', 'I am ambivalent about the following move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR))))', 'I am ambivalent about the following move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NAR (DMZ (FRA ENG) (LVP YOR))))', 'I am not ready for a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR))))', 'I am not ready for a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I am ambivalent about the following move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I am ambivalent about the following move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I am ambivalent about the following move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I am ambivalent about the following move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR))))', 'I am ambivalent about the following move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) DSB))))', 'I am ambivalent about the following move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) BLD))))', 'I am ambivalent about the following move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG FLT LVP) BLD))))', 'I am ambivalent about the following move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) REM))))', 'I am ambivalent about the following move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO (ENG WVE))))', 'I am ambivalent about the following move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) HLD))))', 'I agree to do my part in executing the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) MTO YOR))))', 'I agree to do my part in executing the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (DMZ (FRA ENG) (LVP YOR))))', 'Yes, I will agree to a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (YES (PRP (DMZ (FRA ENG ITA) (LVP YOR))))', 'Yes, I will agree to a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I agree to do my part in executing the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I agree to do my part in executing the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I agree to do my part in executing the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I agree to do my part in executing the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) RTO YOR))))', 'I agree to do my part in executing the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) DSB))))', 'I agree to do my part in executing the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) BLD))))', 'I agree to do my part in executing the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG FLT LVP) BLD))))', 'I agree to do my part in executing the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) REM))))', 'I agree to do my part in executing the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO (ENG WVE))))', 'I agree to do my part in executing the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) HLD)))))', 'I agree to do my part in not executing the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR)))))', 'I agree to do my part in not executing the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (DMZ (FRA ENG) (LVP YOR)))))', 'I agree to oppose a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I agree to oppose a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I agree to do my part in not executing the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I agree to do my part in not executing the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I agree to do my part in not executing the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I agree to do my part in not executing the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR)))))', 'I agree to do my part in not executing the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) DSB)))))', 'I agree to do my part in not executing the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) BLD)))))', 'I agree to do my part in not executing the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG FLT LVP) BLD)))))', 'I agree to do my part in not executing the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) REM)))))', 'I agree to do my part in not executing the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO (ENG WVE)))))', 'I agree to do my part in not executing the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) HLD)))))', 'I agree to be ambivalent about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', 'I agree to be ambivalent about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', 'I agree to be mysterious about a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I agree to be mysterious about a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I agree to be ambivalent about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I agree to be ambivalent about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I agree to be ambivalent about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I agree to be ambivalent about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR)))))', 'I agree to be ambivalent about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) DSB)))))', 'I agree to be ambivalent about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) BLD)))))', 'I agree to be ambivalent about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG FLT LVP) BLD)))))', 'I agree to be ambivalent about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) REM)))))', 'I agree to be ambivalent about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO (ENG WVE)))))', 'I agree to be ambivalent about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) HLD))))', 'I will not execute the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) MTO YOR))))', 'I will not execute the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (DMZ (FRA ENG) (LVP YOR))))', 'I will not accept a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (REJ (PRP (DMZ (FRA ENG ITA) (LVP YOR))))', 'I will not accept a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I will not execute the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I will not execute the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I will not execute the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I will not execute the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) RTO YOR))))', 'I will not execute the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) DSB))))', 'I will not execute the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) BLD))))', 'I will not execute the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG FLT LVP) BLD))))', 'I will not execute the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) REM))))', 'I will not execute the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO (ENG WVE))))', 'I will not execute the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) HLD)))))', 'I will go ahead and execute the move regardless: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR)))))', 'I will go ahead and execute the move regardless: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (DMZ (FRA ENG) (LVP YOR)))))', 'Despite your request, I will support a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR)))))', 'Despite your request, I will support a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I will go ahead and execute the move regardless: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I will go ahead and execute the move regardless: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I will go ahead and execute the move regardless: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I will go ahead and execute the move regardless: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR)))))', 'I will go ahead and execute the move regardless: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) DSB)))))', 'I will go ahead and execute the move regardless: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) BLD)))))', 'I will go ahead and execute the move regardless: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG FLT LVP) BLD)))))', 'I will go ahead and execute the move regardless: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) REM)))))', 'I will go ahead and execute the move regardless: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO (ENG WVE)))))', 'I will go ahead and execute the move regardless: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) HLD)))))', 'I might go ahead and execute the move regardless: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', 'I might go ahead and execute the move regardless: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', 'Despite your request, I might support a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR)))))', 'Despite your request, I might support a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I might go ahead and execute the move regardless: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I might go ahead and execute the move regardless: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I might go ahead and execute the move regardless: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I might go ahead and execute the move regardless: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR)))))', 'I might go ahead and execute the move regardless: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) DSB)))))', 'I might go ahead and execute the move regardless: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) BLD)))))', 'I might go ahead and execute the move regardless: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG FLT LVP) BLD)))))', 'I might go ahead and execute the move regardless: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) REM)))))', 'I might go ahead and execute the move regardless: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO (ENG WVE)))))', 'I might go ahead and execute the move regardless: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) HLD))))', 'I wish to cancel my proposed move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) MTO YOR))))', 'I wish to cancel my proposed move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (DMZ (FRA ENG) (LVP YOR))))', 'I wish to cancel my proposal regarding a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (CCL (PRP (DMZ (FRA ENG ITA) (LVP YOR))))', 'I wish to cancel my proposal regarding a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I wish to cancel my proposed move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I wish to cancel my proposed move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I wish to cancel my proposed move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I wish to cancel my proposed move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) RTO YOR))))', 'I wish to cancel my proposed move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) DSB))))', 'I wish to cancel my proposed move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) BLD))))', 'I wish to cancel my proposed move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG FLT LVP) BLD))))', 'I wish to cancel my proposed move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) REM))))', 'I wish to cancel my proposed move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO (ENG WVE))))', 'I wish to cancel my proposed move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) HLD)))))', 'I wish to cancel my opposition to the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR)))))', 'I wish to cancel my opposition to the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (DMZ (FRA ENG) (LVP YOR)))))', 'I wish to cancel my proposal against a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I wish to cancel my proposal against a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I wish to cancel my opposition to the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I wish to cancel my opposition to the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I wish to cancel my opposition to the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I wish to cancel my opposition to the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR)))))', 'I wish to cancel my opposition to the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) DSB)))))', 'I wish to cancel my opposition to the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) BLD)))))', 'I wish to cancel my opposition to the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG FLT LVP) BLD)))))', 'I wish to cancel my opposition to the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) REM)))))', 'I wish to cancel my opposition to the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO (ENG WVE)))))', 'I wish to cancel my opposition to the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) HLD)))))', 'I wish to cancel my ambivalence about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', 'I wish to cancel my ambivalence about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', 'I wish to cancel my proposal regarding a Demilitarized Zone in Liverpool and Yorkshire for you and me.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I wish to cancel my proposal regarding a Demilitarized Zone in Liverpool and Yorkshire for you, me and Italy.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I wish to cancel my ambivalence about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I wish to cancel my ambivalence about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I wish to cancel my ambivalence about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I wish to cancel my ambivalence about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR)))))', 'I wish to cancel my ambivalence about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) DSB)))))', 'I wish to cancel my ambivalence about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) BLD)))))', 'I wish to cancel my ambivalence about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG FLT LVP) BLD)))))', 'I wish to cancel my ambivalence about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) REM)))))', 'I wish to cancel my ambivalence about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO (ENG WVE)))))', 'I wish to cancel my ambivalence about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) HLD)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) MTO YOR)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (DMZ (FRA ENG) (LVP YOR)))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) RTO YOR)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) DSB)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) BLD)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG FLT LVP) BLD)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) REM)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO (ENG WVE)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) HLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (DMZ (FRA ENG) (LVP YOR))))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR))))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) DSB))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) BLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG FLT LVP) BLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) REM))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO (ENG WVE))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) HLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (DMZ (FRA ENG) (LVP YOR))))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR))))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) DSB))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) BLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG FLT LVP) BLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) REM))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO (ENG WVE))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (HUH (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', 'I don\'t understand your move proposal.'),
                ('FRM (FRA) (ENG) (HUH (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', 'I don\'t understand your Demilitarized Zone proposal.'),
                ('FRM (FRA) (ENG) (BWX (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', ''),
                ('FRM (FRA) (ENG) (BWX (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', '')
               ]

daide10tests = [
                ('FRM (ENG) (FRA ITA) (PRP (PCE (FRA ITA)))', 'I propose a peace treaty between you.'),
                ('FRM (ENG) (FRA ITA) (PRP (PCE (ENG FRA ITA)))', 'I propose a peace treaty between us.'),
                ('FRM (ENG) (FRA ITA) (PRP (ALY (ENG FRA ITA) VSS (RUS TUR)))', 'I propose an alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (PRP (ALY (FRA ITA) VSS (RUS TUR)))', 'I propose an alliance against Russia and Turkey involving you.'),
                ('FRM (ENG) (FRA) (PRP (ALY (FRA ITA) VSS (RUS TUR)))', 'I propose an alliance against Russia and Turkey involving Italy.'),
                ('FRM (ENG) (FRA ITA) (PRP (DRW))', 'I propose a draw between you and me.'),
                ('FRM (ENG) (FRA ITA) (PRP (DRW (ENG FRA ITA)))', 'I propose a draw between you and me.'),
                ('FRM (ENG) (FRA) (PRP (SLO (FRA)))', 'I propose a solo win by you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (PCE (FRA ITA))))', 'I propose that there not be a peace treaty between you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (PCE (ENG FRA ITA))))', 'I propose that there not be a peace treaty between us.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I propose that there not be an alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (ALY (FRA ITA) VSS (ENG))))', 'I propose that there not be an alliance against me involving you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR))))', 'I propose that there not be an alliance against Russia and Turkey involving you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (DRW)))', 'I do not want a draw between you and me.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (DRW (ENG FRA ITA))))', 'I do not want a draw between you and me.'),
                ('FRM (ENG) (FRA) (PRP (NOT (SLO (FRA))))', 'I do not want a solo win by you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (PCE (FRA ITA))))', 'I am not ready for a peace treaty between you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (PCE (ENG FRA ITA))))', 'I am not ready for a peace treaty between us.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I am not ready for an alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (ALY (FRA ITA) VSS (ENG))))', 'I am not ready for an alliance against me involving you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR))))', 'I am not ready for an alliance against Russia and Turkey involving you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (DRW)))', 'I am not ready for a draw between you and me.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (DRW (ENG FRA ITA))))', 'I am not ready for a draw between you and me.'),
                ('FRM (ENG) (FRA) (PRP (NAR (SLO (FRA))))', 'I am not ready for a solo win by you.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (PCE (FRA ITA))))', 'Yes, I will agree to a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (PCE (ENG FRA ITA))))', 'Yes, I will agree to a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'Yes, I will agree to an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (ALY (FRA ITA) VSS (RUS TUR))))', 'Yes, I will agree to an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (DRW)))', 'Yes, I will agree to a draw between you and me.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (DRW (ENG FRA ITA))))', 'Yes, I will agree to a draw between you and me.'),
                ('FRM (FRA) (ENG) (YES (PRP (SLO (FRA))))', 'Yes, I will agree to a solo win by me.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (PCE (FRA ITA)))))', 'I agree to oppose a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (PCE (ENG FRA ITA)))))', 'I agree to oppose a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I agree to oppose an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', 'I agree to oppose an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (DRW))))', 'I agree to oppose a draw between you and me.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (DRW (ENG FRA ITA)))))', 'I agree to oppose a draw between you and me.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (SLO (FRA)))))', 'I agree to oppose a solo win by me.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (PCE (FRA ITA)))))', 'I agree to be mysterious about a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (PCE (ENG FRA ITA)))))', 'I agree to be mysterious about a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I agree to be mysterious about an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', 'I agree to be mysterious about an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (DRW))))', 'I agree to be mysterious about a draw between you and me.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (DRW (ENG FRA ITA)))))', 'I agree to be mysterious about a draw between you and me.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (SLO (FRA)))))', 'I agree to be mysterious about a solo win by me.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (PCE (FRA ITA))))', 'I will not accept a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (PCE (ENG FRA ITA))))', 'I will not accept a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I will not accept an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (ALY (FRA ITA) VSS (RUS TUR))))', 'I will not accept an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (DRW)))', 'I will not accept a draw between you and me.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (DRW (ENG FRA ITA))))', 'I will not accept a draw between you and me.'),
                ('FRM (FRA) (ENG) (REJ (PRP (SLO (FRA))))', 'I will not accept a solo win by me.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (PCE (FRA ITA)))))', 'Despite your request, I will support a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (PCE (ENG FRA ITA)))))', 'Despite your request, I will support a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'Despite your request, I will support an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', 'Despite your request, I will support an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (DRW))))', 'Despite your request, I will support a draw between you and me.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (DRW (ENG FRA ITA)))))', 'Despite your request, I will support a draw between you and me.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (SLO (FRA)))))', 'Despite your request, I will support a solo win by me.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (PCE (FRA ITA)))))', 'Despite your request, I might support a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (PCE (ENG FRA ITA)))))', 'Despite your request, I might support a peace treaty between us.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'Despite your request, I might support an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', 'Despite your request, I might support an alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (DRW))))', 'Despite your request, I might support a draw between you and me.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (DRW (ENG FRA ITA)))))', 'Despite your request, I might support a draw between you and me.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (SLO (FRA)))))', 'Despite your request, I might support a solo win by me.'),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (PCE (FRA ITA))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (PCE (ENG FRA ITA))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (DRW)))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (DRW (ENG FRA ITA))))', ''),
                ('FRM (FRA) (ENG) (BWX (PRP (SLO (FRA))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (PCE (FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (PCE (ENG FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (ALY (FRA ITA) VSS (RUS TUR))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (DRW))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (DRW (ENG FRA ITA)))))', ''),
                ('FRM (FRA) (ENG) (BWX (PRP (NOT (SLO (FRA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (PCE (FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (PCE (ENG FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (DRW))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (DRW (ENG FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (SLO (FRA)))))', ''),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (PCE (FRA ITA))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (PCE (ENG FRA ITA))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (ALY (FRA ITA) VSS (RUS TUR))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (DRW)))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (DRW (ENG FRA ITA))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG) (HUH (PRP (SLO (FRA))))', 'I don\'t understand your solo proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (PCE (FRA ITA)))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (PCE (ENG FRA ITA)))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (DRW))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (DRW (ENG FRA ITA)))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG) (HUH (PRP (NOT (SLO (FRA)))))', 'I don\'t understand your solo proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (PCE (FRA ITA)))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (PCE (ENG FRA ITA)))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (DRW))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (DRW (ENG FRA ITA)))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (SLO (FRA)))))', 'I don\'t understand your solo proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (PCE (FRA ITA))))', 'I wish to cancel my proposal regarding a peace treaty between you.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (PCE (ENG FRA ITA))))', 'I wish to cancel my proposal regarding a peace treaty between us.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I wish to cancel my proposal regarding an alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (ALY (FRA ITA) VSS (RUS TUR))))', 'I wish to cancel my proposal regarding an alliance against Russia and Turkey involving you.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (DRW)))', 'I wish to cancel my proposal regarding a draw between you and me.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (DRW (ENG FRA ITA))))', 'I wish to cancel my proposal regarding a draw between you and me.'),
                ('FRM (ENG) (FRA) (CCL (PRP (SLO (FRA))))', 'I wish to cancel my proposal regarding a solo win by you.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (PCE (FRA ITA)))))', 'I wish to cancel my proposal against a peace treaty between you.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (PCE (ENG FRA ITA)))))', 'I wish to cancel my proposal against a peace treaty between us.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my proposal against an alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my proposal against an alliance against Russia and Turkey involving you.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (DRW))))', 'I wish to cancel my proposal against a draw between you and me.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (DRW (ENG FRA ITA)))))', 'I wish to cancel my proposal against a draw between you and me.'),
                ('FRM (ENG) (FRA) (CCL (PRP (NOT (SLO (FRA)))))', 'I wish to cancel my proposal against a solo win by you.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (PCE (FRA ITA)))))', 'I wish to cancel my proposal regarding a peace treaty between you.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (PCE (ENG FRA ITA)))))', 'I wish to cancel my proposal regarding a peace treaty between us.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my proposal regarding an alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my proposal regarding an alliance against Russia and Turkey involving you.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (DRW))))', 'I wish to cancel my proposal regarding a draw between you and me.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (DRW (ENG FRA ITA)))))', 'I wish to cancel my proposal regarding a draw between you and me.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (SLO (FRA)))))', 'I wish to cancel my proposal regarding a solo win by France.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (PCE (FRA ITA)))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (PCE (ENG FRA ITA)))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (ALY (FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (DRW))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (DRW (ENG FRA ITA)))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA) (CCL (YES (PRP (SLO (FRA)))))', 'I wish to cancel my agreement to your solo proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (PCE (FRA ITA))))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (PCE (ENG FRA ITA))))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR))))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR))))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (DRW)))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (DRW (ENG FRA ITA))))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA) (CCL (YES (PRP (NOT (SLO (FRA))))))', 'I wish to cancel my agreement to your solo proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (PCE (FRA ITA))))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (PCE (ENG FRA ITA))))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR))))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR))))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (DRW)))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (DRW (ENG FRA ITA))))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (SLO (FRA))))))', 'I wish to cancel my agreement to your solo proposal.'),
                ('FRM (ENG) (FRA) (FCT (PCE (ENG ITA)))', 'It is a fact that there is a a peace treaty between me and Italy.'),
                ('FRM (ENG) (FRA) (FCT (PCE (TUR ITA)))', 'It is a fact that there is a a peace treaty between Turkey and Italy.'),
                ('FRM (ENG) (FRA) (FCT (ALY (ENG ITA) VSS (RUS TUR)))', 'It is a fact that there is a an alliance against Russia and Turkey involving Italy.'),
                ('FRM (ENG) (FRA) (FCT (ALY (TUR ITA) VSS (RUS)))', 'It is a fact that there is a an alliance against Russia involving Turkey and Italy.'),
                ('FRM (ENG) (FRA) (FCT (ALY (TUR ITA) VSS (ENG)))', 'It is a fact that there is a an alliance against me involving Turkey and Italy.'),
                ('FRM (ENG) (FRA) (FCT (DRW))', 'It is likely that there is a draw between you and me.'),
                ('FRM (ENG) (FRA) (FCT (DRW (ENG FRA ITA)))', 'It is likely that there is a draw between you, me and Italy.'),
                ('FRM (ENG) (FRA) (FCT (SLO (ENG)))', 'It is likely that there is a solo win by me.'),
                ('FRM (ENG) (FRA) (FCT (SLO (TUR)))', 'It is likely that there is a solo win by Turkey.'),
                ('FRM (ENG) (FRA) (FCT (NOT (PCE (ENG ITA))))', 'It is not the case that there is a peace treaty between me and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (PCE (FRA ITA))))', 'It is not the case that there is a peace treaty between you and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (PCE (RUS ITA))))', 'It is not the case that there is a peace treaty between Russia and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (ALY (ENG ITA) VSS (RUS TUR))))', 'It is not the case that there is an alliance against Russia and Turkey involving Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (ALY (RUS ITA) VSS (ENG))))', 'It is not the case that there is an alliance against me involving Russia and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (ALY (RUS ITA) VSS (FRA))))', 'It is not the case that there is an alliance against you involving Russia and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (DRW)))', 'It is not the case that there is a draw between you and me.'),
                ('FRM (ENG) (FRA) (FCT (NOT (DRW (ENG FRA ITA))))', 'It is not the case that there is a draw between you, me and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (SLO (ENG))))', 'It is not the case that there is a solo win by me.'),
                ('FRM (ENG) (FRA) (FCT (NAR (PCE (ENG ITA))))', 'I do not know if there is a peace treaty between me and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NAR (ALY (ENG ITA) VSS (RUS TUR))))', 'I do not know if there is an alliance against Russia and Turkey involving Italy.'),
                ('FRM (ENG) (FRA) (FCT (NAR (DRW)))', 'I do not know that there is a draw between you and me.'),
                ('FRM (ENG) (FRA) (FCT (NAR (SLO (ENG))))', 'I do not know that there is a solo win by me.'),
                ('BORK BORK BORK', 'Ahem.'),
                ('', 'Ahem.')
]

class PowerListTest(unittest.TestCase):
  """ Tests building lists of countries from trigrams. """
  def test(self):
    self.assertEqual(helpers.listOfPowers(['ENG'], 'ENG', ['FRA', 'ITA']), 'me')
    self.assertEqual(helpers.listOfPowers(['FRA'], 'ENG', ['FRA']), 'you')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ENG'], 'ENG', ['FRA']), 'you and me')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ENG'], 'ENG', ['FRA'], case='Subjective'), 'you and I')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ENG', 'ITA'], 'ENG', ['FRA']), 'you, me and Italy')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ENG', 'ITA'], 'ENG', ['FRA'], case='Subjective'), 'you, I and Italy')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA'], 'ENG', ['FRA', 'ITA']), 'you')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA'], 'ENG', ['FRA']), 'you and Italy')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA', 'RUS'], 'ENG', ['FRA']), 'you, Italy and Russia')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA', 'RUS'], 'ENG', ['FRA', 'ITA']), 'you and Russia')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA', 'RUS'], 'ENG', ['TUR']), 'France, Italy and Russia')

class ParseTest(unittest.TestCase):
  """ Tests parsing of various quasi-compliant DAIDE strings. """
  def test(self):
    for curdaide in parsetests:
      self.assertEqual(len(helpers.daide2lists(curdaide)), 4)

class Level10Test(unittest.TestCase):
  """ Tests different level 10 press expressions in Objective tone. """
  def test(self):
    for sentencepair in daide10tests:
      print('Testing ' + sentencepair[0])
      self.assertEqual(PRESSGLOSS.daide2gloss(sentencepair[0], ['Objective']), sentencepair[1])

class Level20Test(unittest.TestCase):
  """ Tests different level 20 press expressions in Objective tone. """
  def test(self):
    for sentencepair in daide20tests:
#      print('Testing ' + sentencepair[0])
      self.assertEqual(PRESSGLOSS.daide2gloss(sentencepair[0], ['Objective']), sentencepair[1])

if __name__ == '__main__':
  unittest.main()
