# -*- coding: utf-8 -*-
""" Test pressgloss library. """

# Standard library imports
import unittest

# pressgloss imports
import pressgloss.core as PRESSGLOSS
import pressgloss.helpers as helpers

parsetests = ['FRM (ENG) (FRA  ITA) (PRP (PCE (FRA ITA) ))',
              'FRM (ENG) (FRA ITA) (PRP (PCE (FRA ITA) ))',
              'FRM (ENG) (FRA  ITA) (PRP (PCE (FRA ITA)))',
              'FRM ( ENG) (FRA  ITA) (PRP (PCE (FRA ITA) ))',
              'FRM (ENG) (FRA ITA) (PRP (PCE (ENG FRA ITA)))',
              'FRM (ENG) (FRA ITA) (PRP (ALY (ENG FRA ITA) VSS (RUS TUR)))']

daide20tests = [
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) HLD)))', 'I propose the following move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) MTO YOR)))', 'I propose the following move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (DMZ (FRA ENG) (LVP YOR)))', 'I propose that you and I agree to create a Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (DMZ (FRA ENG ITA) (LVP YOR)))', 'I propose that you, I and Italy agree to create a Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))', 'I propose the following move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))', 'I propose the following move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))', 'I propose the following move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))', 'I propose the following move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) RTO YOR)))', 'I propose the following move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) DSB)))', 'I propose the following move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) BLD)))', 'I propose the following move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG FLT LVP) BLD)))', 'I propose the following move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (XDO ((ENG AMY LVP) REM)))', 'I propose the following move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (XDO (ENG WVE)))', 'I propose the following move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) HLD))))', 'I do not support the following move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR))))', 'I do not support the following move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NOT (DMZ (FRA ENG) (LVP YOR))))', 'I propose that you and I do not create a Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR))))', 'I propose that you, I and Italy do not create a Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I do not support the following move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I do not support the following move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I do not support the following move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I do not support the following move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR))))', 'I do not support the following move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) DSB))))', 'I do not support the following move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) BLD))))', 'I do not support the following move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG FLT LVP) BLD))))', 'I do not support the following move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO ((ENG AMY LVP) REM))))', 'I do not support the following move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NOT (XDO (ENG WVE))))', 'I do not support the following move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) HLD))))', 'I am ambivalent about the following move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR))))', 'I am ambivalent about the following move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NAR (DMZ (FRA ENG) (LVP YOR))))', 'I am ambivalent about you and I creating a Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR))))', 'I am ambivalent about you, I and Italy creating a Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I am ambivalent about the following move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I am ambivalent about the following move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I am ambivalent about the following move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I am ambivalent about the following move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR))))', 'I am ambivalent about the following move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) DSB))))', 'I am ambivalent about the following move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) BLD))))', 'I am ambivalent about the following move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG FLT LVP) BLD))))', 'I am ambivalent about the following move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO ((ENG AMY LVP) REM))))', 'I am ambivalent about the following move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (PRP (NAR (XDO (ENG WVE))))', 'I am ambivalent about the following move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) HLD))))', 'I agree to do my part in executing the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) MTO YOR))))', 'I agree to do my part in executing the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (DMZ (FRA ENG) (LVP YOR))))', 'I agree to do my part in respecting the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (DMZ (FRA ENG ITA) (LVP YOR))))', 'I agree to do my part in respecting the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I agree to do my part in executing the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I agree to do my part in executing the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I agree to do my part in executing the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I agree to do my part in executing the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) RTO YOR))))', 'I agree to do my part in executing the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) DSB))))', 'I agree to do my part in executing the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) BLD))))', 'I agree to do my part in executing the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG FLT LVP) BLD))))', 'I agree to do my part in executing the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO ((ENG AMY LVP) REM))))', 'I agree to do my part in executing the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (XDO (ENG WVE))))', 'I agree to do my part in executing the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) HLD)))))', 'I agree to do my part in not executing the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR)))))', 'I agree to do my part in not executing the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (DMZ (FRA ENG) (LVP YOR)))))', 'I agree to do my part in ignoring the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I agree to do my part in ignoring the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I agree to do my part in not executing the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I agree to do my part in not executing the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I agree to do my part in not executing the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I agree to do my part in not executing the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR)))))', 'I agree to do my part in not executing the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) DSB)))))', 'I agree to do my part in not executing the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) BLD)))))', 'I agree to do my part in not executing the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG FLT LVP) BLD)))))', 'I agree to do my part in not executing the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO ((ENG AMY LVP) REM)))))', 'I agree to do my part in not executing the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (XDO (ENG WVE)))))', 'I agree to do my part in not executing the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) HLD)))))', 'I agree that I may or may not participate in the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', 'I agree that I may or may not participate in the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', 'I agree that I may or may not respect the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I agree that I may or may not respect the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I agree that I may or may not participate in the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I agree that I may or may not participate in the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I agree that I may or may not participate in the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I agree that I may or may not participate in the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR)))))', 'I agree that I may or may not participate in the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) DSB)))))', 'I agree that I may or may not participate in the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) BLD)))))', 'I agree that I may or may not participate in the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG FLT LVP) BLD)))))', 'I agree that I may or may not participate in the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO ((ENG AMY LVP) REM)))))', 'I agree that I may or may not participate in the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (YES (PRP (NAR (XDO (ENG WVE)))))', 'I agree that I may or may not participate in the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) HLD))))', 'I will not execute the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) MTO YOR))))', 'I will not execute the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (DMZ (FRA ENG) (LVP YOR))))', 'I will not respect the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (DMZ (FRA ENG ITA) (LVP YOR))))', 'I will not respect the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I will not execute the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I will not execute the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I will not execute the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I will not execute the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) RTO YOR))))', 'I will not execute the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) DSB))))', 'I will not execute the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) BLD))))', 'I will not execute the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG FLT LVP) BLD))))', 'I will not execute the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO ((ENG AMY LVP) REM))))', 'I will not execute the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (XDO (ENG WVE))))', 'I will not execute the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) HLD)))))', 'I will go ahead and execute the move regardless: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR)))))', 'I will go ahead and execute the move regardless: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (DMZ (FRA ENG) (LVP YOR)))))', 'Regardless, I will still respect the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR)))))', 'Regardless, I will still respect the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I will go ahead and execute the move regardless: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I will go ahead and execute the move regardless: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I will go ahead and execute the move regardless: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I will go ahead and execute the move regardless: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR)))))', 'I will go ahead and execute the move regardless: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) DSB)))))', 'I will go ahead and execute the move regardless: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) BLD)))))', 'I will go ahead and execute the move regardless: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG FLT LVP) BLD)))))', 'I will go ahead and execute the move regardless: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO ((ENG AMY LVP) REM)))))', 'I will go ahead and execute the move regardless: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (XDO (ENG WVE)))))', 'I will go ahead and execute the move regardless: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) HLD)))))', 'I am not ambiguous about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', 'I am not ambiguous about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', 'I am not ambiguous about the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I am not ambiguous about the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I am not ambiguous about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I am not ambiguous about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I am not ambiguous about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I am not ambiguous about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR)))))', 'I am not ambiguous about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) DSB)))))', 'I am not ambiguous about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) BLD)))))', 'I am not ambiguous about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG FLT LVP) BLD)))))', 'I am not ambiguous about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO ((ENG AMY LVP) REM)))))', 'I am not ambiguous about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NAR (XDO (ENG WVE)))))', 'I am not ambiguous about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) HLD))))', 'I wish to cancel my proposed move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) MTO YOR))))', 'I wish to cancel my proposed move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (DMZ (FRA ENG) (LVP YOR))))', 'I wish to cancel my proposed Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (DMZ (FRA ENG ITA) (LVP YOR))))', 'I wish to cancel my proposed Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))', 'I wish to cancel my proposed move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))', 'I wish to cancel my proposed move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))', 'I wish to cancel my proposed move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))', 'I wish to cancel my proposed move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) RTO YOR))))', 'I wish to cancel my proposed move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) DSB))))', 'I wish to cancel my proposed move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) BLD))))', 'I wish to cancel my proposed move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG FLT LVP) BLD))))', 'I wish to cancel my proposed move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO ((ENG AMY LVP) REM))))', 'I wish to cancel my proposed move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (XDO (ENG WVE))))', 'I wish to cancel my proposed move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) HLD)))))', 'I wish to cancel my opposition to the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR)))))', 'I wish to cancel my opposition to the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (DMZ (FRA ENG) (LVP YOR)))))', 'I wish to cancel my opposition to the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I wish to cancel my opposition to the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I wish to cancel my opposition to the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I wish to cancel my opposition to the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I wish to cancel my opposition to the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I wish to cancel my opposition to the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR)))))', 'I wish to cancel my opposition to the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) DSB)))))', 'I wish to cancel my opposition to the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) BLD)))))', 'I wish to cancel my opposition to the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG FLT LVP) BLD)))))', 'I wish to cancel my opposition to the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO ((ENG AMY LVP) REM)))))', 'I wish to cancel my opposition to the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NOT (XDO (ENG WVE)))))', 'I wish to cancel my opposition to the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) HLD)))))', 'I wish to cancel my ambivalence about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', 'I wish to cancel my ambivalence about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', 'I wish to cancel my ambivalence about the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I wish to cancel my ambivalence about the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I wish to cancel my ambivalence about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I wish to cancel my ambivalence about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I wish to cancel my ambivalence about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I wish to cancel my ambivalence about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR)))))', 'I wish to cancel my ambivalence about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) DSB)))))', 'I wish to cancel my ambivalence about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) BLD)))))', 'I wish to cancel my ambivalence about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG FLT LVP) BLD)))))', 'I wish to cancel my ambivalence about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO ((ENG AMY LVP) REM)))))', 'I wish to cancel my ambivalence about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (PRP (NAR (XDO (ENG WVE)))))', 'I wish to cancel my ambivalence about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) HLD)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) MTO YOR)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (DMZ (FRA ENG) (LVP YOR)))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (DMZ (FRA ENG ITA) (LVP YOR)))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) SUP (FRA AMY YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) RTO YOR)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) DSB)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) BLD)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG FLT LVP) BLD)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO ((ENG AMY LVP) REM)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (XDO (ENG WVE)))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) HLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) MTO YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (DMZ (FRA ENG) (LVP YOR))))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (DMZ (FRA ENG ITA) (LVP YOR))))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) RTO YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) DSB))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) BLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG FLT LVP) BLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO ((ENG AMY LVP) REM))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NOT (XDO (ENG WVE))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) HLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain holds their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain moves their Army from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (DMZ (FRA ENG) (LVP YOR))))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (DMZ (FRA ENG ITA) (LVP YOR))))))', 'I wish to cancel my agreement to your proposal regarding the Demilitarized Zone in Liverpool and Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR) MTO LON))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool so France can move their Army from Yorkshire into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) SUP (FRA AMY YOR)))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain provides support with their Army in Liverpool for France to hold their Army in Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG FLT NTH) CVY (FRA AMY BRE) CTO LON))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Fleet in the North Sea convoys France\'s Army from Brest into London.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY YOR) CTO LON VIA (NAO IRI NTH)))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Yorkshire moves by convoy to London following this path: the North Atlantic, the Irish Sea and the North Sea.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) RTO YOR))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army retreats from Liverpool to Yorkshire.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) DSB))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain\'s Army in Liverpool retreats from the board.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) BLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG FLT LVP) BLD))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain builds a new Fleet in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO ((ENG AMY LVP) REM))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain removes their Army in Liverpool.'),
                ('FRM (FRA) (ENG) (CCL (YES (PRP (NAR (XDO (ENG WVE))))))', 'I wish to cancel my agreement to your proposal about the move: Great Britain waives their next build phase.'),
                ('FRM (FRA) (ENG) (HUH (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', 'I don\'t understand your move proposal.'),
                ('FRM (FRA) (ENG) (HUH (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', 'I don\'t understand your Demilitarized Zone proposal.'),
                ('FRM (FRA) (ENG) (BWX (PRP (NAR (XDO ((ENG AMY LVP) MTO YOR)))))', ''),
                ('FRM (FRA) (ENG) (BWX (PRP (NAR (DMZ (FRA ENG) (LVP YOR)))))', '')
               ]

daide10tests = [
                ('FRM (ENG) (FRA ITA) (PRP (PCE (FRA ITA)))', 'Would you two agree to end any conflict between you and sign a peace treaty?'),
                ('FRM (ENG) (FRA ITA) (PRP (PCE (ENG FRA ITA)))', 'Let us sign a peace treaty together.'),
                ('FRM (ENG) (FRA ITA) (PRP (ALY (ENG FRA ITA) VSS (RUS TUR)))', 'Let us declare an alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (PRP (ALY (FRA ITA) VSS (RUS TUR)))', 'Would you two ally against Russia and Turkey?'),
                ('FRM (ENG) (FRA) (PRP (ALY (FRA ITA) VSS (RUS TUR)))', 'Would you declare an alliance against Russia and Turkey with Italy?'),
                ('FRM (ENG) (FRA ITA) (PRP (DRW))', 'Are you amenable to a draw?'),
                ('FRM (ENG) (FRA ITA) (PRP (DRW (ENG FRA ITA)))', 'Are you amenable to a draw between Great Britain, France and Italy?'),
                ('FRM (ENG) (FRA) (PRP (SLO (FRA)))', 'You should go for a solo win, I won\'t get in your way.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (PCE (FRA ITA))))', 'I propose that you end your treaty together.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (PCE (ENG FRA ITA))))', 'I propose that we end any promises of peace between us.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'We should not ally against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (ALY (FRA ITA) VSS (ENG))))', 'Please do not form an alliance against me.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR))))', 'Don\'t ally together against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (DRW)))', 'I wouldn\'t agree to a draw with you two.'),
                ('FRM (ENG) (FRA ITA) (PRP (NOT (DRW (ENG FRA ITA))))', 'I wouldn\'t agree to a draw between Great Britain, France and Italy.'),
                ('FRM (ENG) (FRA) (PRP (NOT (SLO (FRA))))', 'I wouldn\'t try for a solo win if I were you.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (PCE (FRA ITA))))', 'You shouldn\'t sign a peace agreement together.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (PCE (ENG FRA ITA))))', 'I propose we don\'t make peace at this time.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I propose we make no alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (ALY (FRA ITA) VSS (ENG))))', 'Please do not form an alliance against me.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR))))', 'I propose you don\'t ally together against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (DRW)))', 'There is no draw condition between us.'),
                ('FRM (ENG) (FRA ITA) (PRP (NAR (DRW (ENG FRA ITA))))', 'There is no draw condition between us.'),
                ('FRM (ENG) (FRA) (PRP (NAR (SLO (FRA))))', 'I won\'t pledge support of your solo win.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (PCE (FRA ITA))))', 'Yes, I will sign a peace treaty between me and Italy.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (PCE (ENG FRA ITA))))', 'Yes, I will sign a peace treaty between me, Great Britain and Italy.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'Yes, I will sign an alliance between me, Great Britain and Italy against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (ALY (FRA ITA) VSS (RUS TUR))))', 'Yes, I will sign an alliance between me and Italy against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (DRW)))', 'Yes, I agree to a draw.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (DRW (ENG FRA ITA))))', 'Yes, I agree to a draw between our three countries.'),
                ('FRM (FRA) (ENG) (YES (PRP (SLO (FRA))))', 'I will use your support to pursue a solo win.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (PCE (FRA ITA)))))', 'I will end any peace treaties between me and Italy.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (PCE (ENG FRA ITA)))))', 'I will end any peace treaties between me and Great Britain and Italy.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I will not ally with Great Britain and Italy against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', 'I will not ally with Italy against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (DRW))))', 'You\'re right, it\'s not the time for a draw.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NOT (DRW (ENG FRA ITA)))))', 'You\'re right, it\'s not the time for a draw.'),
                ('FRM (FRA) (ENG) (YES (PRP (NOT (SLO (FRA)))))', 'I will not pursue a solo win.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (PCE (FRA ITA)))))', 'I agree, no peace with Italy.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (PCE (ENG FRA ITA)))))', 'I agree, no peace with Great Britain and Italy.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I agree, no alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', 'I agree, no alliance against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (DRW))))', 'I agree, a draw is not right at this time.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (DRW (ENG FRA ITA)))))', 'I agree, a draw is not right at this time.'),
                ('FRM (FRA) (ENG ITA) (YES (PRP (NAR (SLO (FRA)))))', 'If I will pursue a solo win, I won\'t rely on your support.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (PCE (FRA ITA))))', 'I will not sign a peace deal with Italy.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (PCE (ENG FRA ITA))))', 'I will not sign a peace deal with Great Britain and Italy.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I will not ally with Great Britain and Italy against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (ALY (FRA ITA) VSS (RUS TUR))))', 'I will not ally with Italy against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (DRW)))', 'I reject a draw.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (DRW (ENG FRA ITA))))', 'I reject a draw between us.'),
                ('FRM (FRA) (ENG) (REJ (PRP (SLO (FRA))))', 'I am not pursuing a solo win at this time.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (PCE (FRA ITA)))))', 'I won\'t promise not to make peace with Italy.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (PCE (ENG FRA ITA)))))', 'I think a peace treaty would be a good idea between the three of us.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I think an alliance against Russia and Turkey is a good idea.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', 'I think an alliance against Russia and Turkey is a good idea.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (DRW))))', 'I will still be seeking a draw condition.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NOT (DRW (ENG FRA ITA)))))', 'I will still be seeking a draw condition.'),
                ('FRM (FRA) (ENG) (REJ (PRP (NOT (SLO (FRA)))))', 'I will pursue a solo win if I want to.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (PCE (FRA ITA)))))', 'I can\'t promise I won\'t pursue peace between me and Italy.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (PCE (ENG FRA ITA)))))', 'I can\'t promise I won\'t pursue peace between me and Great Britain and Italy.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I can\'t promise not to ally against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', 'I can\'t promise not to ally against Russia and Turkey.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (DRW))))', 'I think a draw is very possible now.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (DRW (ENG FRA ITA)))))', 'I think a draw is very possible now.'),
                ('FRM (FRA) (ENG ITA) (REJ (PRP (NAR (SLO (FRA)))))', 'A solo win is still on the table if I want to.'),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (PCE (FRA ITA))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (PCE (ENG FRA ITA))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (DRW)))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (DRW (ENG FRA ITA))))', ''),
                ('FRM (FRA) (ENG) (BWX (PRP (SLO (FRA))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (PCE (FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (PCE (ENG FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (ALY (FRA ITA) VSS (RUS TUR))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (DRW))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NOT (DRW (ENG FRA ITA)))))', ''),
                ('FRM (FRA) (ENG) (BWX (PRP (NOT (SLO (FRA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (PCE (FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (PCE (ENG FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (DRW))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (DRW (ENG FRA ITA)))))', ''),
                ('FRM (FRA) (ENG ITA) (BWX (PRP (NAR (SLO (FRA)))))', ''),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (PCE (FRA ITA))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (PCE (ENG FRA ITA))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (ALY (FRA ITA) VSS (RUS TUR))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (DRW)))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (DRW (ENG FRA ITA))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG) (HUH (PRP (SLO (FRA))))', 'I don\'t understand your solo proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (PCE (FRA ITA)))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (PCE (ENG FRA ITA)))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (DRW))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NOT (DRW (ENG FRA ITA)))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG) (HUH (PRP (NOT (SLO (FRA)))))', 'I don\'t understand your solo proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (PCE (FRA ITA)))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (PCE (ENG FRA ITA)))))', 'I don\'t understand your peace proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', 'I don\'t understand your alliance proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (DRW))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (DRW (ENG FRA ITA)))))', 'I don\'t understand your draw proposal.'),
                ('FRM (FRA) (ENG ITA) (HUH (PRP (NAR (SLO (FRA)))))', 'I don\'t understand your solo proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (PCE (FRA ITA))))', 'I wish to cancel the request that you sign a peace deal.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (PCE (ENG FRA ITA))))', 'I wish to cancel the request that we sign a peace deal.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (ALY (ENG FRA ITA) VSS (RUS TUR))))', 'I wish to cancel the proposed alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (ALY (FRA ITA) VSS (RUS TUR))))', 'I wish to cancel the proposed alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (DRW)))', 'I wish to cancel the proposed draw.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (DRW (ENG FRA ITA))))', 'I wish to cancel the proposed draw.'),
                ('FRM (ENG) (FRA) (CCL (PRP (SLO (FRA))))', 'I wish to cancel my support for your solo win.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (PCE (FRA ITA)))))', 'I wish to cancel my opposition to your peace deal.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (PCE (ENG FRA ITA)))))', 'I wish to cancel my opposition to our peace deal.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my opposition to the proposed alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my opposition to the proposed alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (DRW))))', 'I wish to cancel my opposition to a draw.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NOT (DRW (ENG FRA ITA)))))', 'I wish to cancel my opposition to a draw.'),
                ('FRM (ENG) (FRA) (CCL (PRP (NOT (SLO (FRA)))))', 'I wish to cancel my opposition to your solo win.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (PCE (FRA ITA)))))', 'I wish to cancel my opposition to your peace deal.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (PCE (ENG FRA ITA)))))', 'I wish to cancel my opposition to our peace deal.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my opposition to the proposed alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my opposition to the proposed alliance against Russia and Turkey.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (DRW))))', 'I wish to cancel my opposition to a draw.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (DRW (ENG FRA ITA)))))', 'I wish to cancel my opposition to a draw.'),
                ('FRM (ENG) (FRA ITA) (CCL (PRP (NAR (SLO (FRA)))))', 'I wish to cancel my opposition to your solo win.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (PCE (FRA ITA)))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (PCE (ENG FRA ITA)))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (ALY (ENG FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (ALY (FRA ITA) VSS (RUS TUR)))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (DRW))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (DRW (ENG FRA ITA)))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA) (CCL (YES (PRP (SLO (FRA)))))', 'I wish to cancel my agreement to your solo proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (PCE (FRA ITA))))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (PCE (ENG FRA ITA))))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (ALY (ENG FRA ITA) VSS (RUS TUR))))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (ALY (FRA ITA) VSS (RUS TUR))))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (DRW)))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NOT (DRW (ENG FRA ITA))))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA) (CCL (YES (PRP (NOT (SLO (FRA))))))', 'I wish to cancel my agreement to your solo proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (PCE (FRA ITA))))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (PCE (ENG FRA ITA))))))', 'I wish to cancel my agreement to your peace proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (ALY (ENG FRA ITA) VSS (RUS TUR))))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (ALY (FRA ITA) VSS (RUS TUR))))))', 'I wish to cancel my agreement to your alliance proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (DRW)))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (DRW (ENG FRA ITA))))))', 'I wish to cancel my agreement to your draw proposal.'),
                ('FRM (ENG) (FRA ITA) (CCL (YES (PRP (NAR (SLO (FRA))))))', 'I wish to cancel my agreement to your solo proposal.'),
                ('FRM (ENG) (FRA) (FCT (PCE (ENG ITA)))', 'I have a peace deal with Italy.'),
                ('FRM (ENG) (FRA) (FCT (PCE (TUR ITA)))', 'There is a peace deal between Turkey and Italy.'),
                ('FRM (ENG) (FRA) (FCT (ALY (ENG ITA) VSS (RUS TUR)))', 'I have an alliance with Italy against Russia and Turkey.'),
                ('FRM (ENG) (FRA) (FCT (ALY (TUR ITA) VSS (RUS)))', 'There is an alliance between Turkey and Italy against Russia.'),
                ('FRM (ENG) (FRA) (FCT (ALY (TUR ITA) VSS (ENG)))', 'There is an alliance between Turkey and Italy against me.'),
                ('FRM (ENG) (FRA) (FCT (DRW))', 'I am in a draw condition.'),
                ('FRM (ENG) (FRA) (FCT (DRW (ENG FRA ITA)))', 'I am in a draw condition with you and Italy.'),
                ('FRM (ENG) (FRA) (FCT (SLO (ENG)))', 'I am going for a solo win.'),
                ('FRM (ENG) (FRA) (FCT (SLO (TUR)))', 'Turkey is going for a solo win.'),
                ('FRM (ENG) (FRA) (FCT (NOT (PCE (ENG ITA))))', 'I broke my peace deal with Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (PCE (FRA ITA))))', 'There is no longer a peace deal between you and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (PCE (RUS ITA))))', 'There is no longer a peace deal between Russia and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (ALY (ENG ITA) VSS (RUS TUR))))', 'I do not have an alliance with Italy against Russia and Turkey.'),
                ('FRM (ENG) (FRA) (FCT (NOT (ALY (RUS ITA) VSS (ENG))))', 'There is no alliance between Russia and Italy against me.'),
                ('FRM (ENG) (FRA) (FCT (NOT (ALY (RUS ITA) VSS (FRA))))', 'There is no alliance between Russia and Italy against you.'),
                ('FRM (ENG) (FRA) (FCT (NOT (DRW)))', 'I am not in a draw condition.'),
                ('FRM (ENG) (FRA) (FCT (NOT (DRW (ENG FRA ITA))))', 'I am not in a draw condition with you and Italy.'),
                ('FRM (ENG) (FRA) (FCT (NOT (SLO (ENG))))', 'I am not going for a solo win.'),
                ('FRM (ENG) (FRA) (FCT (NAR (PCE (ENG ITA))))', 'I have no peace deal with Italy.'),
                ('FRM (ENG) (FRA) (FCT (NAR (ALY (ENG ITA) VSS (RUS TUR))))', 'I do not have an alliance with Italy against Russia and Turkey.'),
                ('FRM (ENG) (FRA) (FCT (NAR (DRW)))', 'A draw is not something I\'ve considered.'),
                ('FRM (ENG) (FRA) (FCT (NAR (SLO (ENG))))', 'A solo win is not something I\'ve considered.'),
                ('BORK BORK BORK', 'Ahem.'),
                ('', 'Ahem.')
]

class PowerListTest(unittest.TestCase):
  """ Tests building lists of countries from trigrams. """
  def test(self):
    self.assertEqual(helpers.listOfPowers(['ENG'], 'ENG', ['FRA', 'ITA']), 'me')
    self.assertEqual(helpers.listOfPowers(['FRA'], 'ENG', ['FRA']), 'you')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ENG'], 'ENG', ['FRA']), 'you and me')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ENG', 'ITA'], 'ENG', ['FRA']), 'you, me and Italy')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA'], 'ENG', ['FRA', 'ITA']), 'you')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA'], 'ENG', ['FRA']), 'you and Italy')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA', 'RUS'], 'ENG', ['FRA']), 'you, Italy and Russia')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA', 'RUS'], 'ENG', ['FRA', 'ITA']), 'you and Russia')
    self.assertEqual(helpers.listOfPowers(['FRA', 'ITA', 'RUS'], 'ENG', ['TUR']), 'France, Italy and Russia')

class ParseTest(unittest.TestCase):
  """ Tests parsing of various quasi-compliant DAIDE strings. """
  def test(self):
    for curdaide in parsetests:
      self.assertEqual(len(helpers.daide2lists(curdaide)), 4)

class Level10Test(unittest.TestCase):
  """ Tests different level 10 press expressions in Objective tone. """
  def test(self):
    for sentencepair in daide10tests:
      print('Testing ' + sentencepair[0])
      self.assertEqual(PRESSGLOSS.daide2gloss(sentencepair[0], ['Objective']), sentencepair[1])

class Level20Test(unittest.TestCase):
  """ Tests different level 20 press expressions in Objective tone. """
  def test(self):
    for sentencepair in daide20tests:
      print('Testing ' + sentencepair[0])
      self.assertEqual(PRESSGLOSS.daide2gloss(sentencepair[0], ['Objective']), sentencepair[1])

if __name__ == '__main__':
  unittest.main()
